name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. .env 파일 생성
      - name: Create .env file
        run: |
          echo "VITE_APP_NAVERMAPS_CLIENT_ID=${{ secrets.VITE_APP_NAVERMAPS_CLIENT_ID }}" >> .env
          echo "VITE_APP_KAKAO_CLIENT_ID=${{ secrets.VITE_APP_KAKAO_CLIENT_ID }}" >> .env
          echo "VITE_APP_KAKAO_INTEGRITY_VALUE=${{ secrets.VITE_APP_KAKAO_INTEGRITY_VALUE }}" >> .env
          echo "VITE_APP_KAKAO_SDK_VERSION=${{ secrets.VITE_APP_KAKAO_SDK_VERSION }}" >> .env

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 5. Vite로 프로젝트 빌드
      - name: Build project
        run: npm run build

      # 6. GitHub Pages에 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
